DocRec/DocList/urls.py
from django.urls import path

from . import views

app_name = 'DocList'
urlpatterns = [
    path('', views.main, name='main'),
    path('page/<int:_page>', views.index, name='index'),
    path('<int:_id>/', views.docs, name='docs'),
]

DocRec/DocRec/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('DocList/', include('DocList.urls'))
]

DocRec/DocList/models.py
from django.db import models

class Title(models.Model):
    _text = models.CharField(max_length=200)
    _date = models.DateTimeField('date published')
    def __str__(self):
        return self._text

class Content(models.Model):
    title = models.ForeignKey(Title, on_delete=models.CASCADE)
    _text = models.TextField()
    def __str__(self):
        return self._text

class DocUrl(models.Model):
    title = models.ForeignKey(Title, on_delete=models.CASCADE)
    _text = models.CharField(max_length=100)
    def __str__(self):
        return self._text

DocRec/DocList/views.py
import psycopg2
import pandas as pd
import os
import csv

from django.shortcuts import render, redirect

from . import recommend, init, database

def main(request):
    init.main()
    return redirect('page/1')

def index(request, _page):
    q = request.GET.get('q', '')
    if q:
        docs_df = database.GetDF()
        docs_list = recommend.SearchDoc(docs_df, q)
    else:
        # sign_info = "host='localhost' dbname ='docdb' user='postgres' password='********'"
        # sign = psycopg2.connect(sign_info)
        # cursor = sign.cursor()
        fnum = _page * 20
        snum = (_page - 1) * 20
        docs_list = []
        with open(os.path.join(database.BASE_DIR + '/', 'data.csv'),
                  'r', encoding='utf-8') as db:
            reader = csv.reader(db)
            for data in reader:
                if int(data[0]) > snum:
                    docs_list.append(data)
                if int(data[0]) == fnum:
                    break

        # sql = "SELECT * FROM doclist WHERE id < '{}' AND id >= '{}'".format(fnum, snum)
        # cursor.execute(sql)
        # docs_list = cursor.fetchall()
        # cursor.close()
        # sign.close()
    return render(request, 'DocList/index.html', {
        'docs_list':
            docs_list,
        'previous':
            _page-1,
        'next':
            _page+1
    })

def docs(request, _id):
    # sign_info = "host='localhost' dbname ='docdb' user='postgres' password='********'"
    # sign = psycopg2.connect(sign_info)
    # cursor = sign.cursor()
    #
    # sql = "SELECT title, url, content FROM doclist WHERE id = '{}'".format(_id)
    # cursor.execute(sql)
    # doc = cursor.fetchone()
    # cursor.close()
    # sign.close()
    page = _id // 20 + 1
    docs_df = database.GetDF()
    doc = docs_df.iloc[_id]
    related, frequency = recommend.Top10_Docs(docs_df, _id)
    return render(request, 'DocList/docs.html', {
        'doc':
            doc,
        'page':
            page,
        'related':
            related,
        'frequency':
            frequency[:10]
    })

DocRec/DocList/templates/DocList/docs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> </title>
    <style media="screen">
      #warp{
        max-width: 100%;
      }
      #related{
        float:left;
      }
      #word{
        float:right;
      }
      #back{
        clear:both;
      }
    </style>
</head>
<body>
<h1>{{ doc.0 }}</h1>

<div>
  <div id="warp">
    {{ doc.2 }}
  </div>
  <div id="related">
    <h2>유사 문서</h2>
    <ol>
        {% for doc in related %}
        <li>{{ doc }}</li>
        {% endfor %}
    </ol>
  </div>
  <div id="word">
    <h2>Top ranking word</h2>
    <ol>
        {% for word in frequency %}
        <li>{{ word }}</li>
        {% endfor %}
    </ol>
    </div>
    <div id="back">
      <a href="{% url 'DocList:index' page %}">Back</a>
    </div>
</div>
</body>
</html>

DocRec/DocList/templates/DocList/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>
  <form action="" method="get">
  <input type="text" name="q" value="{{ q }}">
  <input type="submit" value="search">
  </form>

    {% if docs_list %}
        <ol>
            {% for doc in docs_list %}
            <li><a href="{% url 'DocList:docs' doc.0 %}">{{ doc.1 }}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <p>No Docs are available.</p>
    {% endif %}
    {% if previous > 0 %}
        <a href="{% url 'DocList:index' previous %}">Back</a>
    {% endif %}
    <a href="{% url 'DocList:index' next %}">Next</a>
</body>
</html>